package negocio;

import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class frmClientes extends javax.swing.JFrame {

    DefaultComboBoxModel departamentos = new DefaultComboBoxModel();
    DefaultComboBoxModel nombresDepartamentos = new DefaultComboBoxModel();
    DefaultComboBoxModel municipios = new DefaultComboBoxModel();
    DefaultComboBoxModel nombresMunicipios = new DefaultComboBoxModel();
    DefaultTableModel modeloClientes = new DefaultTableModel(); 
    ArrayList<String> encabezados= new ArrayList<>();
    
    ResultSet rstDepartamentos = null;
    ResultSet rstMunicipios = null;
    ResultSet rstClientes = null;
    Departamentos departamento = new Departamentos();
    Municipios municipio = new Municipios();
    Clientes cliente = new Clientes();

    
    public frmClientes() {
        initComponents();
        
        rstDepartamentos = departamento.llenarDepartamentos();
        try {
            while (rstDepartamentos.next()){
                departamentos.addElement(rstDepartamentos.getInt(1));
                nombresDepartamentos.addElement(rstDepartamentos.getString(2));
            }
            cmbDepartamentos.setModel(nombresDepartamentos);
            lblDepartamentoSeleccionado.setText(String.valueOf(departamentos.getElementAt(0)));
        } catch (SQLException ex) {
            Logger.getLogger(frmClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblApellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        lblDepartamento = new javax.swing.JLabel();
        cmbDepartamentos = new javax.swing.JComboBox<>();
        lblMunicipio = new javax.swing.JLabel();
        cmbMunicipios = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        lblDepartamentoSeleccionado = new javax.swing.JLabel();
        lblMunicipioSeleccionado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblId.setText("Id");
        getContentPane().add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 32, -1, -1));
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 29, 40, -1));

        lblNombre.setText("Nombre");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 60, 289, -1));

        lblApellido.setText("Apellido");
        getContentPane().add(lblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 101, -1, -1));
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 98, 289, -1));

        lblDepartamento.setText("Departamento");
        getContentPane().add(lblDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 139, -1, -1));

        cmbDepartamentos.setModel(departamentos);
        cmbDepartamentos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbDepartamentosItemStateChanged(evt);
            }
        });
        getContentPane().add(cmbDepartamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 136, 289, -1));

        lblMunicipio.setText("Municipio");
        getContentPane().add(lblMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 178, -1, -1));

        cmbMunicipios.setModel(municipios);
        cmbMunicipios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbMunicipiosItemStateChanged(evt);
            }
        });
        getContentPane().add(cmbMunicipios, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 175, 289, -1));

        btnAgregar.setText("Agregar cliente");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, -1, -1));

        lblDepartamentoSeleccionado.setText("   ");
        getContentPane().add(lblDepartamentoSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 139, 25, -1));

        lblMunicipioSeleccionado.setText("     ");
        getContentPane().add(lblMunicipioSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 178, 25, -1));

        tblClientes.setModel(modeloClientes);
        jScrollPane1.setViewportView(tblClientes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 226, 738, 255));

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbDepartamentosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbDepartamentosItemStateChanged
        int posicion;
        posicion = cmbDepartamentos.getSelectedIndex();
        lblDepartamentoSeleccionado.setText(String.valueOf(departamentos.getElementAt(posicion)));
        
        //Llenando el cmbMunicipios mediante un modelo
        municipios.removeAllElements();
        nombresMunicipios.removeAllElements();
        try{
            rstMunicipios = municipio.llenarMunicipios(Integer.parseInt(lblDepartamentoSeleccionado.getText()));
            while (rstMunicipios.next()) {
                municipios.addElement(rstMunicipios.getString(2));
                nombresMunicipios.addElement(rstMunicipios.getString(3));
            }
        cmbMunicipios.setModel(nombresMunicipios);
        lblMunicipioSeleccionado.setText(String.valueOf(municipios.getElementAt(0)));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }


        
    }//GEN-LAST:event_cmbDepartamentosItemStateChanged

    private void cmbMunicipiosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbMunicipiosItemStateChanged
        int posicion;
        posicion = cmbMunicipios.getSelectedIndex();
        lblMunicipioSeleccionado.setText(String.valueOf(municipios.getElementAt(posicion)));
    }//GEN-LAST:event_cmbMunicipiosItemStateChanged

    public void Columnas(){
          encabezados.clear();
          encabezados.add("Id");
          encabezados.add("Nombre");
          encabezados.add("Apellido");
          encabezados.add("Departamento");
          encabezados.add("Municipio");
          encabezados.add("Nombre Departamento");
          encabezados.add("Nombre Municipio");
      }
    
    public void reinicio(){
        modeloClientes.setColumnCount(0);
        modeloClientes.setRowCount(0);
    }
    
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        int cuantasColumnas;
        int columna;
        cliente.insertar(txtId.getText(), txtNombre.getText(), txtApellido.getText(), Integer.parseInt(lblDepartamentoSeleccionado.getText()), Integer.parseInt(lblMunicipioSeleccionado.getText()));
        JOptionPane.showMessageDialog(null, "Guardado con éxito");
        reinicio();
        Columnas();
        rstClientes=null;
        rstClientes=cliente.llenarTabla();
        
        
        try {
            ResultSetMetaData rstClientesMD = rstClientes.getMetaData();
            cuantasColumnas = rstClientesMD.getColumnCount();
            
            //llenar la tabla con encabezados
            for (columna=0; columna<cuantasColumnas; columna++){
                modeloClientes.addColumn(encabezados.get(columna));
            }
            
            
            while (rstClientes.next()){
                Object[]fila = new Object[columna];
                for (int campo=0;campo<cuantasColumnas;campo++){
                    fila[campo]=rstClientes.getObject(campo+1);
                }     
                modeloClientes.addRow(fila); 
            }
        
        //finaliza llenado de tabla
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

        tblClientes.setModel(modeloClientes);
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        Limpiar();
        txtId.requestFocus();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void Limpiar(){
        txtId.setText("");
        txtApellido.setText("");
        txtNombre.setText("");
        cmbDepartamentos.setSelectedIndex(0);
        cmbMunicipios.setSelectedIndex(0);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cmbDepartamentos;
    private javax.swing.JComboBox<String> cmbMunicipios;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblDepartamento;
    private javax.swing.JLabel lblDepartamentoSeleccionado;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblMunicipio;
    private javax.swing.JLabel lblMunicipioSeleccionado;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
